const regions = {
  India: {
    name: "India",
    center: [22, 77],
    zoom: 4.5,
    currency: "₹",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["IST"],
  },
  "United States": {
    name: "United States",
    center: [37.8, -96],
    zoom: 4,
    currency: "$",
    speed: "mph",
    distance: "miles",
    volume: "gallons",
    timezone: ["EST", "CST", "MST", "PST"],
  },
  China: {
    name: "China",
    center: [35.9, 104.2],
    zoom: 4.5,
    currency: "¥",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["CST"],
  },
  Japan: {
    name: "Japan",
    center: [36.2, 138.4],
    zoom: 6,
    currency: "¥",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["JST"],
  },
  Germany: {
    name: "Germany",
    center: [51, 9],
    zoom: 6,
    currency: "€",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["CET"],
  },
  United_Kingdom: {
    name: "United Kingdom",
    center: [54.5, -3],
    zoom: 6,
    currency: "£",
    speed: "mph",
    distance: "miles",
    volume: "liters",
    timezone: ["GMT"],
  },
  France: {
    name: "France",
    center: [46.8, 2.3],
    zoom: 6,
    currency: "€",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["CET"],
  },
  Italy: {
    name: "Italy",
    center: [41.9, 12.6],
    zoom: 6,
    currency: "€",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["CET"],
  },
  Brazil: {
    name: "Brazil",
    center: [-14.2, -51.9],
    zoom: 4,
    currency: "R$",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["BRT"],
  },
  Canada: {
    name: "Canada",
    center: [60.4, -96.7],
    zoom: 4,
    currency: "C$",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["EST", "CST", "MST", "PST"],
  },
  South_Korea: {
    name: "South Korea",
    center: [36.3, 127.6],
    zoom: 6,
    currency: "₩",
    speed: "kmph",
    distance: "kilometers",
    volume: "liters",
    timezone: ["KST"],
  },
};

export default regions;
